version: "3.7"

services:
    client:
        build:
            context: ./client
        command: npm start
        volumes:
            - ./client/src:/usr/app/src
        ports:
            - '3000:3000'
        tty: true
        stdin_open: true
        environment:
            - API_PORT:3001
            - API_URL:api
        depends_on:
            - server
    server:
        build:
            context: ./server
        command: npm start
        volumes:
            - ./server/src:/usr/app/src
        ports:
            - '3001:3001'
        environment:
            - PORT:3001
            - CORS_PORT:3000
            - CORS_URL:frontend

